import { beforeEach, expect, it, vi } from 'vitest'
const storage = vi.hoisted(() => ({ loadGameSave: vi.fn(), saveGame: vi.fn().mockResolvedValue(undefined) }))
vi.mock('../../src/platform/storage/game-storage', () => storage)
beforeEach(() => { vi.resetModules(); storage.loadGameSave.mockReset(); storage.saveGame.mockClear() })
it('sanitizes legacy or corrupt records without losing valid scores', async () => {
  storage.loadGameSave.mockResolvedValue({ best: { good: 4, bad: '2', negative: -1, infinite: Infinity }, flags: ['sudoku-4', 9, null, 'sudoku-4'], levels: { sokoban: 3, bad: -1, fractional: 2.2 } })
  const { loadProgress, summarizeProgress } = await import('../../src/games/puzzle-kit/progress')
  const progress = await loadProgress()
  expect(progress).toEqual({ best: { good: 4 }, flags: ['sudoku-4'], levels: { sokoban: 3 } })
  expect(summarizeProgress(progress).sudoku).toContain('难度')
})
it('shares reads, rejects invalid writes and persists independent snapshots in order', async () => {
  storage.loadGameSave.mockResolvedValue(null)
  const { loadProgress, recordBest, recordLevel, recordFlag } = await import('../../src/games/puzzle-kit/progress')
  await Promise.all([loadProgress(), loadProgress()])
  expect(storage.loadGameSave).toHaveBeenCalledTimes(1)
  recordBest('a', -1); recordLevel('a', 1.5)
  recordBest('a', 8); recordBest('a', 4); recordBest('a', 6); recordFlag('done')
  await vi.waitFor(() => expect(storage.saveGame).toHaveBeenCalledTimes(3))
  const values = storage.saveGame.mock.calls.map(call => call[1])
  expect(values[0].best.a).toBe(8)
  expect(values.at(-1)).toEqual({ best: { a: 4 }, flags: ['done'], levels: {} })
})
it('recovers from unavailable storage', async () => {
  storage.loadGameSave.mockRejectedValue(new Error('unavailable'))
  const { loadProgress } = await import('../../src/games/puzzle-kit/progress')
  expect(await loadProgress()).toEqual({ best: {}, flags: [], levels: {} })
})
it('keeps assisted runs separate and summarizes modes without double counting', async () => {
  storage.loadGameSave.mockResolvedValue(null)
  const { recordRun, loadProgress, summarizeProgress } = await import('../../src/games/puzzle-kit/progress')
  recordRun('pipes-3', 20, false); recordRun('pipes-3', 1, true)
  recordRun('sokoban-L0', 2, false); recordRun('sokoban-L0', 2, true)
  await vi.waitFor(() => expect(storage.saveGame).toHaveBeenCalledTimes(4))
  const progress = await loadProgress()
  expect(progress.best['pipes-3:solo']).toBe(20)
  expect(summarizeProgress(progress).pipes).toContain('20步 · 独立')
  expect(summarizeProgress(progress).sokoban).toBe('已过 1 关')
})
